version: '3.8'

services:
  telegram-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram-mcp
    # Load environment variables from a .env file in the same directory
    env_file:
      - stack.env
    # Expose port 8000 for HTTP/SSE transport
    ports:
      - "8000:8000"
    # Optional: Uncomment the following lines to mount a local directory
    # for persisting the Telegram session file if NOT using TELEGRAM_SESSION_STRING.
    # Replace './telegram_sessions' with your desired host path.
    # volumes:
    #   - ./telegram_sessions:/app
    restart: unless-stopped 
